version: '3.9'
services:

  food-database:
    image: "mysql:latest"
    container_name: food-database
    volumes:
      - ./database:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - LANG=C.UTF_8
    healthcheck:
      test: ["CMD", 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p$$MYSQL_ROOT_PASSWORD' ]
      timeout: 20s
      retries: 10
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']

  food-backend:
    build: ./backend
    container_name: food-backend
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=food-database
      - DB_NAME=food_db
      - DB_USER=root
      - DB_PWD=root
    restart: on-failure
    depends_on:
      food-database:
        condition: service_healthy
    links:
      - food-database